name: PHP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0, 8.1]
        wordpress: [latest, '6.1', '6.0', '5.9']
        include:
          - php: 7.4
            wordpress: '5.8'
          - php: 7.4
            wordpress: '5.7'
        exclude:
          - php: 8.1
            wordpress: '5.9'

    name: PHP ${{ matrix.php }} / WP ${{ matrix.wordpress }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, gd, exif, iconv
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest

    - name: PHP CodeSniffer
      run: |
        composer phpcs

    - name: PHPStan
      run: |
        composer phpstan

    - name: Install WordPress test environment
      run: |
        bash bin/install-wp-tests.sh wordpress_test root root localhost ${{ matrix.wordpress }}

    - name: PHPUnit
      run: |
        composer phpunit