name: PHP Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    name: PHP lint and PHPCS

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # v2.32.0

    - name: Install dependencies
      run: |
        composer install --prefer-dist --no-progress --no-suggest

    - name: PHP CodeSniffer
      run: |
        composer phpcs

    - name: PHPStan
      run: |
        composer phpstan